### ISSUE TITLE
here is a few screenshots showing the issue

### ISSUE THREAD

**Issue by Loko415** [Yimura/GTA5-Backend#1]
![image](https://user-images.githubusercontent.com/67609719/155070094-11201a5f-12d2-453e-ae40-46bfef2f1d26.png)

**Comment by Loko415** [comment]
{
    "credentials": {
        "mongodb": {
            "dev": {
                "auth": {
                    "user": "loko",
                    "password": "lokoman12345",
                    "host": "mongodb://localhost:27017",
                    "database": "api"
                },
                "options": {
                    "useNewUrlParser": true,
                    "useUnifiedTopology": true,
                    "useFindAndModify": true,
                    "useCreateIndex": true
                }
            },
            "prod": {
                "auth": {
                    "user": "loko",
                    "password": "lokoman12345",
                    "host": "mongodb://localhost:27017",
                    "database": "api"
                },
                "options": {
                    "useNewUrlParser": true,
                    "useUnifiedTopology": true,
                    "useFindAndModify": false,
                    "useCreateIndex": true
                }
            }
        }
    }
}

**Comment by Loko415** [comment]
{
    "credentials": {
        "mongodb": {
            "dev": {
                "auth": {
                    "user": "loko",
                    "password": "lokoman12345",
                    "host": "mongodb://localhost:27017",
                    "database": "api"
                },
                "options": {
                    "useNewUrlParser": true,
                    "useUnifiedTopology": true,
                    "useFindAndModify": true,
                    "useCreateIndex": true
                }
            },
            "prod": {
                "auth": {
                    "user": "loko",
                    "password": "lokoman12345",
                    "host": "mongodb://localhost:27017",
                    "database": "api"
                },
                "options": {
                    "useNewUrlParser": true,
                    "useUnifiedTopology": true,
                    "useFindAndModify": false,
                    "useCreateIndex": true
                }
            }
        }
    }
}

**Comment by Loko415** [comment]
thats my file

**Comment by Loko415** [comment]
![image](https://user-images.githubusercontent.com/67609719/155070252-d0899e80-733b-482b-9145-0b78b56a0f8e.png)

**Comment by Loko415** [comment]
MongooseServerSelectionError: getaddrinfo ENOTFOUND mongodb
    at NativeConnection.Connection.openUri (C:\Users\customer\Downloads\AA gta menu\GTA5-Backend\node_modules\mongoose\lib\connection.js:846:32)
    at C:\Users\customer\Downloads\AA gta menu\GTA5-Backend\node_modules\mongoose\lib\index.js:351:10
    at C:\Users\customer\Downloads\AA gta menu\GTA5-Backend\node_modules\mongoose\lib\helpers\promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (C:\Users\customer\Downloads\AA gta menu\GTA5-Backend\node_modules\mongoose\lib\helpers\promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (C:\Users\customer\Downloads\AA gta menu\GTA5-Backend\node_modules\mongoose\lib\index.js:1149:10)
    at Mongoose.connect (C:\Users\customer\Downloads\AA gta menu\GTA5-Backend\node_modules\mongoose\lib\index.js:350:20)
    at MongoDB.init (file:///C:/Users/customer/Downloads/AA%20gta%20menu/GTA5-Backend/src/modules/MongoDB/index.js:38:22)
    at Proxy.initModules (file:///C:/Users/customer/Downloads/AA%20gta%20menu/GTA5-Backend/src/managers/Modules.js:119:72)
    at Proxy.load (file:///C:/Users/customer/Downloads/AA%20gta%20menu/GTA5-Backend/src/managers/Modules.js:52:25)
    at async Main.start (file:///C:/Users/customer/Downloads/AA%20gta%20menu/GTA5-Backend/src/Main.js:24:9) {
  reason: TopologyDescription {
    type: 'Single',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map(1) { 'mongodb:27017' => [ServerDescription] },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: null
  }
}

**Comment by Yimura** [comment]
Why don't you use a single commit to explain everything?

**Comment by Loko415** [comment]
MongoError: Authentication failed.
    at MessageStream.messageHandler (C:\Users\customer\Downloads\AA gta menu\GTA5-Backend\node_modules\mongodb\lib\cmap\connection.js:272:20)
    at MessageStream.emit (events.js:400:28)
    at processIncomingData (C:\Users\customer\Downloads\AA gta menu\GTA5-Backend\node_modules\mongodb\lib\cmap\message_stream.js:144:12)
    at MessageStream._write (C:\Users\customer\Downloads\AA gta menu\GTA5-Backend\node_modules\mongodb\lib\cmap\message_stream.js:42:5)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at MessageStream.Writable.write (internal/streams/writable.js:303:10)
    at Socket.ondata (internal/streams/readable.js:726:22)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  ok: 0,
  code: 18,
  codeName: 'AuthenticationFailed'
}

**Comment by Loko415** [comment]
[16:03:52] [MONGODB/INFO] Established connection to MongoDB successfully.
[16:03:52] [REST/VERBOSE] Registered all routes:
Map(8) {
  '/api' => Root { _m: Main { _a: [Object], _c: [Object] } },
  '/api/v1/auth/create_session' => CreateSession { _m: Main { _a: [Object], _c: [Object] } },
  '/api/v1/vehicle/handling/create' => CreateHandlingProfile { _m: Main { _a: [Object], _c: [Object] } },
  '/api/v1/vehicle/handling/get_by_share_code' => GetHandlingDataByShareCode {
    _m: Main { _a: [Object], _c: [Object] }
  },
  '/api/v1/vehicle/handling/get_mine' => GetMyHandlingProfiles { _m: Main { _a: [Object], _c: [Object] } },
  '/api/v1/vehicle/handling/get_saved' => GetSavedHandlingProfiles { _m: Main { _a: [Object], _c: [Object] } },
  '/api/v1/vehicle/handling/save_profile' => SaveProfile { _m: Main { _a: [Object], _c: [Object] } },
  '/api/v1/vehicle/handling/update' => UpdateHandlingProfile { _m: Main { _a: [Object], _c: [Object] } }
}
[16:03:52] [WEB/INFO] Starting Webserver...
[16:03:52] [WEB/INFO] Webserver is ready.
users.createIndex {"rockstar_id":1} { unique: true, background: true }
users.createIndex {"username":1} { unique: true, background: true }

**Comment by Loko415** [comment]
working?

**Comment by Loko415** [comment]
[16:12:16][   INFO/api.hpp:79]: Host is down, unable to create session.
[16:12:16][   INFO/api.hpp:79]: Host is down, unable to create session.
[16:12:16][   INFO/api.hpp:79]: Host is down, unable to create session.
[16:12:16][   INFO/api.hpp:79]: Host is down, unable to create session.
[16:12:16][   INFO/api.hpp:79]: Host is down, unable to create session.
[16:12:16][   INFO/api.hpp:79]: Host is down, unable to create session.
[16:12:16][   INFO/api.hpp:79]: Host is down, unable to create session.
[16:12:16][   INFO/api.hpp:79]: Host is down, unable to create session.
[16:12:16][   INFO/api.hpp:79]: Host is down, unable to create session.
[16:12:16][   INFO/api.hpp:79]: Host is down, unable to create session.
[16:12:16][   INFO/api.hpp:79]: Host is down, unable to create session.
[16:12:16][   INFO/api.hpp:79]: Host is down, unable to create session.
[16:12:16][   INFO/api.hpp:79]: Host is down, unable to create session.
[16:12:16][   INFO/api.hpp:79]: Host is down, unable to create session.
[16:12:16][   INFO/api.hpp:79]: Host is down, unable to create session.
[16:12:16][   INFO/api.hpp:79]: Host is down, unable to create session.
[16:12:16][   INFO/api.hpp:79]: Host is down, unable to create session.
[16:12:16][   INFO/api.hpp:79]: Host is down, unable to create session.
[16:12:16][   INFO/api.hpp:79]: Host is down, unable to create session.
[16:12:16][   INFO/api.hpp:79]: Host is down, unable to create session.

**Comment by Loko415** [comment]
eiving request from client. Ending connection from remote","attr":{"error":{"code":141,"codeName":"SSLHandshakeFailed","errmsg":"SSL handshake received but server is started without SSL support"},"remote":"127.0.0.1:52636","connectionId":7231}}
{"t":{"$date":"2022-02-22T16:12:27.390+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn7231","msg":"Connection ended","attr":{"remote":"127.0.0.1:52636","uuid":"efecc66b-344b-45b9-8e70-23560c44af8f","connectionId":7231,"connectionCount":3}}
{"t":{"$date":"2022-02-22T16:12:27.411+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"127.0.0.1:52637","uuid":"5a2cf4d9-1489-4586-9ef5-68e96abed2d9","connectionId":7232,"connectionCount":4}}
{"t":{"$date":"2022-02-22T16:12:27.413+00:00"},"s":"I",  "c":"NETWORK",  "id":22988,   "ctx":"conn7232","msg":"Error receiving request from client. Ending connection from remote","attr":{"error":{"code":141,"codeName":"SSLHandshakeFailed","errmsg":"SSL handshake received but server is started without SSL support"},"remote":"127.0.0.1:52637","connectionId":7232}}
{"t":{"$date":"2022-02-22T16:12:27.414+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn7232","msg":"Connection ended","attr":{"remote":"127.0.0.1:52637","uuid":"5a2cf4d9-1489-4586-9ef5-68e96abed2d9","connectionId":7232,"connectionCount":3}}
{"t":{"$date":"2022-02-22T16:12:27.433+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"127.0.0.1:52638","uuid":"26d0d281-b1fa-4f89-becd-845fbcc339e4","connectionId":7233,"connectionCount":4}}
{"t":{"$date":"2022-02-22T16:12:27.434+00:00"},"s":"I",  "c":"NETWORK",  "id":22988,   "ctx":"conn7233","msg":"Error receiving request from client. Ending connection from remote","attr":{"error":{"code":141,"codeName":"SSLHandshakeFailed","errmsg":"SSL handshake received but server is started without SSL support"},"remote":"127.0.0.1:52638","connectionId":7233}}
{"t":{"$date":"2022-02-22T16:12:27.435+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn7233","msg":"Connection ended","attr":{"remote":"127.0.0.1:52638","uuid":"26d0d281-b1fa-4f89-becd-845fbcc339e4","connectionId":7233,"connectionCount":3}}

**Comment by Loko415** [comment]
[16:14:11] [REST/ERROR] An error occured on "/api/v1/auth/create_session":
MongooseServerSelectionError: Invalid message size: 1347703880, max allowed: 67108864
    at Function.Model.$wrapCallback (C:\Users\customer\Downloads\AA gta menu\GTA5-Backend\node_modules\mongoose\lib\model.js:5087:32)
    at C:\Users\customer\Downloads\AA gta menu\GTA5-Backend\node_modules\mongoose\lib\query.js:4510:21
    at C:\Users\customer\Downloads\AA gta menu\GTA5-Backend\node_modules\mongoose\lib\helpers\promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (C:\Users\customer\Downloads\AA gta menu\GTA5-Backend\node_modules\mongoose\lib\helpers\promiseOrCallback.js:31:10)
    at model.Query.exec (C:\Users\customer\Downloads\AA gta menu\GTA5-Backend\node_modules\mongoose\lib\query.js:4509:10)
    at Object.getUser (file:///C:/Users/customer/Downloads/AA%20gta%20menu/GTA5-Backend/src/modules/Users/structures/models/UserModel.js:38:10)
    at Users.get (file:///C:/Users/customer/Downloads/AA%20gta%20menu/GTA5-Backend/src/modules/Users/index.js:43:26)
    at CreateSession.post (file:///C:/Users/customer/Downloads/AA%20gta%20menu/GTA5-Backend/api/v1/auth/create_session.js:29:40)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async REST._onRequest (file:///C:/Users/customer/Downloads/AA%20gta%20menu/GTA5-Backend/src/modules/REST/index.js:55:17) {
  reason: TopologyDescription {
    type: 'Single',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map(1) { 'localhost:27017' => [ServerDescription] },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: 13
  }
}

**Comment by Loko415** [comment]
how i made a database called api and inside that i put gta

**Comment by Loko415** [comment]
wait does ssl need to be enabled?

**Comment by Yimura** [comment]
Or how about you answer me question? What is the host you put in the api.hpp file?

Just so you know the server runs on plain http protocol.
Inside [data/config.json](https://github.com/Yimura/GTA5-Backend/blob/master/data/config.json) you can find the port the server listens on.

**Comment by Loko415** [comment]
im locally running the server

**Comment by Loko415** [comment]
{
    "development": true,

    "webserver": {
        "port": 27017,

        "allow_headers": [
            "Accept",
            "Authorization",
            "Access-Control-Allow-Headers",
            "Origin",
            "Content-Type",
            "Access-Control-Request-Method",
            "Access-Control-Request-Headers"
        ],
        "allow_methods": [
            "DELETE",
            "GET",
            "HEAD",
            "PATCH",
            "POST",
            "PUT"
        ],
        "origins": [
            "http://localhost:27017"
        ]
    }
}

**Comment by Loko415** [comment]
thanks for helping also

**Comment by Yimura** [comment]
BRUH, are you not smart.

Why would you change the webserver port to the same as the one used by mongodb?
That port should be left alone unless you know what you're doing...

**Comment by Yimura** [comment]
Set the port back to `8080` and then in your api.hpp make sure you're target http://localhost:8080

**Comment by Loko415** [comment]
it targets that and plus /api/v1

**Comment by Loko415** [comment]
MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at NativeConnection.Connection.openUri (C:\Users\customer\Downloads\AA gta menu\GTA5-Backend\node_modules\mongoose\lib\connection.js:846:32)
    at C:\Users\customer\Downloads\AA gta menu\GTA5-Backend\node_modules\mongoose\lib\index.js:351:10
    at C:\Users\customer\Downloads\AA gta menu\GTA5-Backend\node_modules\mongoose\lib\helpers\promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (C:\Users\customer\Downloads\AA gta menu\GTA5-Backend\node_modules\mongoose\lib\helpers\promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (C:\Users\customer\Downloads\AA gta menu\GTA5-Backend\node_modules\mongoose\lib\index.js:1149:10)
    at Mongoose.connect (C:\Users\customer\Downloads\AA gta menu\GTA5-Backend\node_modules\mongoose\lib\index.js:350:20)
    at MongoDB.init (file:///C:/Users/customer/Downloads/AA%20gta%20menu/GTA5-Backend/src/modules/MongoDB/index.js:38:22)
    at Proxy.initModules (file:///C:/Users/customer/Downloads/AA%20gta%20menu/GTA5-Backend/src/managers/Modules.js:119:72)
    at Proxy.load (file:///C:/Users/customer/Downloads/AA%20gta%20menu/GTA5-Backend/src/managers/Modules.js:52:25)
    at async Main.start (file:///C:/Users/customer/Downloads/AA%20gta%20menu/GTA5-Backend/src/Main.js:24:9) {
  reason: TopologyDescription {
    type: 'Single',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map(1) { 'localhost:27017' => [ServerDescription] },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: null
  }
}

**Comment by Loko415** [comment]
i set it to 8080. sos for not reusing messages

**Comment by Loko415** [comment]
servers: Map(1) { 'localhost:27017' => [ServerDescription] },

**Comment by Loko415** [comment]
thats why i changed the port in the first place you see

**Comment by Yimura** [comment]
Yes but that isn't the solution.

**Comment by Loko415** [comment]
what is the solution

**Comment by Yimura** [comment]
Keeping everything default except the auth.json

**Comment by Loko415** [comment]
idk if im doing this in a single comment i apologise if i aint but is it better if i use docker instead?

**Comment by Yimura** [comment]
Did you create a MongoDB user for that specific database?
Try making one just for that database and use that one to authenticate....

**Comment by Yimura** [comment]
That's not an error, that's just an informative log.

**Comment by Loko415** [comment]
![image](https://user-images.githubusercontent.com/67609719/155186952-fb72b2da-39d9-4036-9451-e6e3e798dad9.png)

**Comment by Yimura** [comment]
Ye try making a user for that specific DB, since you're concerned about security, make a user for each DB.

![image](https://user-images.githubusercontent.com/24669514/155190394-0bc891db-4d76-4182-ab37-ce8915d8ae2f.png)

The REST API doesn't authenticate through the admin database, which you're attempting to do and which is also why you're managing to connect to the database.
`?authSource=admin` if you were to remove this you would not be able to authenticate to the specific DB you want to access.
So for the second time, try making a user account for THAT database.

**Comment by Loko415** [comment]
![image](https://user-images.githubusercontent.com/67609719/155191117-e4ad26ea-950b-45a6-872b-167d8c5dfcad.png)
what do i choose

**Comment by Loko415** [comment]
![image](https://user-images.githubusercontent.com/67609719/155191311-07bc404a-8fca-43e4-b565-eeb292706abe.png)
this was 100% the issue i think

**Comment by Loko415** [comment]
[18:00:09] [PROCESS/ERROR] Uncaught process exception:
MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017 that was the error but it keeps running it on port 27017

**Comment by Loko415** [comment]
issue in your code. mongodb folder

**Comment by Loko415** [comment]
![image](https://user-images.githubusercontent.com/67609719/155197337-49d43ab4-59a0-4a63-8d48-468314583560.png)

**Comment by Loko415** [comment]
![image](https://user-images.githubusercontent.com/67609719/155201550-d3b2ec91-52aa-42d9-acc1-6eb3e98d6c43.png)
when i terminate the scripts server it says this "freemode script"

**Comment by Loko415** [comment]
i need the updated code. could you please send me it?

**Comment by Loko415** [comment]
{"t":{"$date":"2022-02-22T20:43:33.341+00:00"},"s":"I",  "c":"NETWORK",  "id":22988,   "ctx":"conn7520","msg":"Error receiving request from client. Ending connection from remote","attr":{"error":{"code":141,"codeName":"SSLHandshakeFailed","errmsg":"SSL handshake received but server is started without SSL support"},"remote":"127.0.0.1:59718","connectionId":7520}}
